// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions android = FirebaseOptions(
//       apiKey: 'AIzaSyCDjaALZ_eNOPqJo_fr4LhlZio_blSBHfU',
//       appId: '1:343131777975:android:34fee950d5020b5d5c1632',
//       messagingSenderId: '343131777975',
//       projectId: 'wafrprovider',
//       storageBucket: 'wafrprovider.appspot.com',
//       androidClientId: '343131777975-0f3tkr1s4rsaeh2bjvu7ajelo2j2pl6g.apps.googleusercontent.com',
//      // deepLinkURLScheme: 'https://soldoutapp.page.link/'
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//       apiKey: 'AIzaSyDohVypsAIY487AtMfFHtMKv66WFGQTyuw',
//       appId: '1:343131777975:ios:2b941af3dfcbdb815c1632',
//       messagingSenderId: '343131777975',
//       projectId: 'wafrprovider',
//       storageBucket: 'wafrprovider.appspot.com',
//       iosClientId: '343131777975-khgfg7aurl16rq9s6hmr19l21kgt1sjq.apps.googleusercontent.com',
//       iosBundleId: 'com.wafr.provider',
//    //   deepLinkURLScheme: 'https://soldoutapp.page.link/'
//   );
//
// }
