// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyCmn0DSpjkH6dr9rCWUtu2AqecTvqEIsYU',
      appId: '1:311327981680:android:f00db5bb7148d4dbb474b5',
      messagingSenderId: '311327981680',
      projectId: 'we-made-4ff1a',
      storageBucket: 'we-made-4ff1a.appspot.com',
      androidClientId: '311327981680-dh3c3p9hru4ajlg7l90i5p0gus54ksea.apps.googleusercontent.com',
     // deepLinkURLScheme: 'https://soldoutapp.page.link/'
  );

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyC0wjVSgIAYfU0Z0pkej1hNOLX9aeUDEQA',
      appId: '1:311327981680:ios:0528d3cf2e4c2653b474b5',
      messagingSenderId: '311327981680',
      projectId: 'we-made-4ff1a',
      storageBucket: 'we-made-4ff1a.appspot.com',
      iosClientId: '311327981680-fubn4v18t1jt9lvqks7lvhjp4ilfoc7k.apps.googleusercontent.com',
      iosBundleId: 'com.wemadeuae',
   //   deepLinkURLScheme: 'https://soldoutapp.page.link/'
  );

}
